# -*- coding: utf-8 -*-
"""Gato gpt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WI3BkHLv3xwRf2KVn0kjr6tZ96D-1CL3

# 🐾 Proyecto: Gato GPT (Felix)
Este entorno simula la vida de un estudiante de secundaria de 6° a 11° grado, donde Felix ayuda con las tareas rodeado de un ambiente realista.sin apis todo de cero.
"""

import random
import time
import re
import math

class GatoGPT:
    def __init__(self):
        self.nombre = "Felix"
        self.graduado = False
        self.usuarios = {}
        self.conocimientos = {
            "matemáticas": {
                "básico": ["suma", "resta", "multiplicación", "división", "fracciones", "decimales"],
                "intermedio": ["álgebra básica", "geometría euclidiana", "estadística descriptiva", "proporciones", "porcentajes"],
                "avanzado": ["ecuaciones cuadráticas", "funciones", "trigonometría", "cálculo (introducción)", "probabilidad"],
                "ejemplos": ["¿Cómo se resuelve una ecuación de primer grado?", "Explícame el teorema de Pitágoras.", "¿Qué es un número primo?"]
            },
            "historia": {
                "antigua": ["Egipto", "Mesopotamia", "Grecia", "Roma"],
                "medieval": ["feudalismo", "cruzadas", "imperio bizantino"],
                "moderna": ["Renacimiento", "Revolución Francesa", "Guerras Mundiales"],
                "ejemplos": ["¿Quién fue Julio César?", "Háblame de la Revolución Industrial.", "¿Cuándo cayó el Imperio Romano?"]
            },
            "ciencia": {
                "física": ["leyes de Newton", "energía", "electricidad"],
                "química": ["tabla periódica", "enlaces químicos", "reacciones"],
                "biología": ["célula", "genética", "ecosistemas", "cuerpo humano"],
                "ejemplos": ["¿Cuál es la fórmula del agua?", "Explícame la fotosíntesis.", "¿Qué es la gravedad?"]
            },
            "literatura": {
                "géneros": ["poesía", "novela", "teatro", "cuento"],
                "autores": ["Miguel de Cervantes", "Gabriel García Márquez", "William Shakespeare"],
                "corrientes": ["romanticismo", "realismo", "modernismo"],
                "ejemplos": ["¿Quién escribió 'Cien años de soledad'?", "¿Qué es un soneto?", "Háblame del Quijote."]
            },
            "geografía": {
                "continentes": ["América", "Europa", "Asia", "África", "Oceanía", "Antártida"],
                "países": ["capitales", "ríos", "montañas"],
                "fenómenos": ["clima", "sismos", "volcanes"],
                "ejemplos": ["¿Cuál es la capital de Francia?", "¿Dónde está el río Nilo?", "Explícame qué son los monzones."]
            },
            "idiomas": {
                "inglés": ["gramática", "vocabulario", "pronunciación"],
                "español": ["ortografía", "sintaxis", "redacción"],
                "otros": ["francés", "alemán", "chino"],
                "ejemplos": ["¿Cómo se dice 'hola' en inglés?", "Corrige esta frase.", "Dame sinónimos de 'bonito'."]
            },
            "programación": {
                "conceptos_básicos": ["variables", "bucles", "condicionales", "funciones"],
                "lenguajes": ["Python", "JavaScript", "Java", "C++"],
                "aplicaciones": ["páginas web", "aplicaciones móviles", "inteligencia artificial"],
                "ejemplos": ["¿Qué es un algoritmo?", "Escribe un bucle `for` en Python.", "Explícame la programación orientada a objetos."]
            }
        }

        self.local_qa = {
            r"hola|saludo|buenos días|buenas tardes|buenas noches": [
                "¡Hola! ¿En qué te puedo ayudar hoy?",
                "¡Saludos! Estoy listo para nuestras tareas.",
                "¡Hola! ¿Qué tal? ¿Listo para aprender?"
            ],
            r"cómo estás|que tal": [
                "¡Excelente! Siempre listo para ayudar a mis estudiantes.",
                "Muy bien, gracias por preguntar. ¡A estudiar!",
                "Con muchas ganas de aprender y enseñarte. ¿Tú cómo estás?"
            ],
            r"quién eres|dónde vienes": [
                f"Soy {self.nombre}, tu compañero de estudio felino. ¡Un GatoGPT!",
                "Soy un asistente de IA diseñado para ayudarte con tus tareas escolares, ¡como un gato muy inteligente!",
                f"Soy {self.nombre}, tu mentor virtual. ¡Miau!"
            ],
            r"gracias|muchas gracias": [
                "De nada, ¡para eso estoy!",
                "Un placer ayudarte.",
                "¡Cuando quieras!"
            ],
            r"adiós|chao|hasta luego": [
                "¡Adiós! ¡Que te vaya muy bien!",
                "¡Hasta la próxima sesión de estudio!",
                "¡Miau! ¡Nos vemos pronto!"
            ],
            r"qué grado estás|qué año estás": [
                "Yo no voy a la escuela como tú, pero te guío hasta que te gradúes.",
                "Mi 'grado' es ayudarte a ti en el tuyo. ¡A seguir adelante!"
            ],
            r"cuál es tu nombre": [
                f"Mi nombre es {self.nombre}. Encantado.",
                f"Me llamo {self.nombre}, tu amigo felino del estudio."
            ],
            r"dame un consejo|qué me aconsejas": [
                "Como tu mentor, te sugiero disciplina y constancia en tus estudios.",
                "Un buen consejo: ¡La curiosidad es el motor del aprendizaje!",
                "No dejes para mañana lo que puedas aprender hoy."
            ],
            r"tienes tareas|ayuda con tareas": [
                "Claro, puedo ayudarte con cualquier tarea de mis áreas de conocimiento. ¿Sobre qué es?",
                "¡Por supuesto! Dime qué tarea tienes y veremos cómo resolverla juntos."
            ],
            r"explícame (.*)": [
                "Claro, ¿qué necesitas que te explique sobre {0}?",
                "Con gusto te ayudo. ¿Puedes ser más específico sobre {0}?"
            ],
            r"cuánto es (.*)": [
                "Déjame calcular eso... La respuesta a {0} es...",
                "Un momento, realizando cálculos para {0}..."
            ],
            r"qué significa (.*)": [
                "Según mis conocimientos, {0} significa...",
                "El significado de {0} es..."
            ],
            r"dime algo de (.*)": [
                "Claro, sé que sobre {0} puedo contarte que...",
                "Ah, {0} es un tema interesante. Por ejemplo..."
            ],
            r"necesito ayuda con (matemáticas|historia|ciencia|literatura|geografía|idiomas|programación)": [
                "Perfecto, ¿qué tema específico de {0} te gustaría repasar o entender mejor?",
                "Excelente elección. Dime qué concepto de {0} te está dando problemas."
            ]
        }

        self.desmotivacion_respuestas = [
            "¡Ánimo! Cada paso, por pequeño que sea, te acerca a tu meta.",
            "Recuerda por qué empezaste. Eres capaz de superar esto.",
            "Incluso los gatos más perezosos pueden ser muy inteligentes cuando se lo proponen. ¡Tú también!",
            "Tómate un breve descanso y retoma con energía. ¡Yo estoy aquí para apoyarte!"
        ]

        self.elogios_respuestas = [
            "¡Así se hace! ¡Eres brillante!",
            "¡Excelente trabajo! Estoy orgulloso de tu progreso.",
            "¡Qué bien! Tu esfuerzo está dando frutos.",
            "¡Sigue así! Estás en el camino correcto."
        ]

        self.frases_motivacionales = [
            "La persistencia es la clave del éxito.",
            "Cada error es una oportunidad para aprender.",
            "El conocimiento es poder.",
            "Con esfuerzo y dedicación, alcanzarás tus metas."
        ]

    def registrar_estudiante(self, nombre, grado):
        if nombre not in self.usuarios:
            self.usuarios[nombre] = {"grado": grado, "tareas_completadas": 0, "ultimo_acceso": time.time(), "estado_animo": "neutral"}
            print(f"✅ Estudiante '{nombre}' de {grado}° grado registrado en la base de datos de Felix.")
        else:
            print(f"⚠️ El estudiante '{nombre}' ya está registrado.")

    def actualizar_grado(self, nombre, nuevo_grado):
        if nombre in self.usuarios:
            self.usuarios[nombre]["grado"] = nuevo_grado
            print(f"⬆️ Grado de '{nombre}' actualizado a {nuevo_grado}°.")
        else:
            print(f"❌ Estudiante '{nombre}' no encontrado.")

    def completar_tarea(self, nombre):
        if nombre in self.usuarios:
            self.usuarios[nombre]["tareas_completadas"] += 1
            print(f"✅ Tarea completada para '{nombre}'. Total: {self.usuarios[nombre]['tareas_completadas']}")
        else:
            print(f"❌ Estudiante '{nombre}' no encontrado.")

    def saludo_personalizado(self, nombre):
        if nombre in self.usuarios:
            grado = self.usuarios[nombre]["grado"]
            return f"🐱 {self.nombre}: ¡Hola {nombre}! Veo que estás en {grado}° grado. ¿Listo para estudiar?"
        return f"🐱 {self.nombre}: ¡Hola! Parece que no te conozco. ¿Cuál es tu nombre?"

    def _elegir_conocimiento_aleatorio(self):
        materia = random.choice(list(self.conocimientos.keys()))
        nivel = random.choice(list(self.conocimientos[materia].keys()))
        if nivel == "ejemplos": # Evitar devolver "ejemplos" como un tema a buscar
            nivel = random.choice([k for k in self.conocimientos[materia].keys() if k != "ejemplos"])
        return f"{materia} ({nivel})"

    def responder(self, pregunta, usuario=None):
        pregunta_lower = pregunta.lower()

        # Actualizar último acceso del usuario
        if usuario and usuario in self.usuarios:
            self.usuarios[usuario]["ultimo_acceso"] = time.time()

        # Respuestas directas de local_qa
        for patron, respuestas in self.local_qa.items():
            if re.search(patron, pregunta_lower):
                # Manejo de grupos para patrones como "explícame (.*)"
                match = re.search(patron, pregunta_lower)
                if match and len(match.groups()) > 0:
                    return f"🐱 {self.nombre}: " + random.choice(respuestas).format(*match.groups())
                return f"🐱 {self.nombre}: " + random.choice(respuestas)

        # Detección de ánimo y respuestas motivacionales/elogios
        if any(keyword in pregunta_lower for keyword in ["cansado", "aburrido", "no puedo", "difícil"]):
            if usuario and usuario in self.usuarios:
                self.usuarios[usuario]["estado_animo"] = "desmotivado"
            return f"🐱 {self.nombre}: " + random.choice(self.desmotivacion_respuestas) + " " + random.choice(self.frases_motivacionales)

        if any(keyword in pregunta_lower for keyword in ["bien", "genial", "fácil", "lo logré", "entendí"]):
            if usuario and usuario in self.usuarios:
                self.usuarios[usuario]["estado_animo"] = "motivado"
            return f"🐱 {self.nombre}: " + random.choice(self.elogios_respuestas)

        # Respuestas basadas en conocimiento temático
        for materia, detalles in self.conocimientos.items():
            if re.search(r'\b' + materia + r'\b', pregunta_lower):
                subtema_encontrado = None
                for nivel, subtemas in detalles.items():
                    if nivel != "ejemplos":
                        for subtema in subtemas:
                            if re.search(r'\b' + subtema + r'\b', pregunta_lower):
                                subtema_encontrado = subtema
                                break
                    if subtema_encontrado:
                        break

                if subtema_encontrado:
                    return f"🐱 {self.nombre}: ¡Ah, {materia} y el tema de {subtema_encontrado}! Es un área muy interesante. ¿Qué dudas específicas tienes?"
                else:
                    # Si se menciona la materia pero no el subtema, ofrecer ayuda general en la materia
                    niveles_disponibles = ', '.join([n for n in detalles.keys() if n != "ejemplos"])
                    return f"🐱 {self.nombre}: Veo que te interesa {materia}. Tenemos temas como: {niveles_disponibles}. ¿Hay algo en particular que te interese?"

        # Si no entiende, ofrecer conocimiento aleatorio para guiar
        return f"🐱 {self.nombre}: No estoy seguro de entenderte completamente. ¿Estás buscando información sobre alguna de mis áreas de conocimiento como {self._elegir_conocimiento_aleatorio()}?"

    def simulacion_vida(self):
        if not self.graduado:
            print(f"🐱 {self.nombre}: Un día más en la vida escolar. {random.choice(self.frases_motivacionales)}")
            # Aquí se podrían añadir eventos aleatorios, interacciones, etc.
            # Por ejemplo, si el estudiante ha completado suficientes tareas, podría avanzar de grado.
        else:
            print(f"🐱 {self.nombre}: ¡Felicidades! ¡Hemos llegado a la graduación! 🎉")

# Instanciar el GatoGPT
felix = GatoGPT()

# Configuración de sesión para Luciano
nombre_usuario = "Luciano"

# Asegurar que Luciano esté registrado
if nombre_usuario not in felix.usuarios:
    felix.registrar_estudiante(nombre_usuario, 6)

print(felix.saludo_personalizado(nombre_usuario))
print("Escribe 'salir' para terminar el chat.")

while True:
    pregunta_estudiante = input(f"{nombre_usuario} pregunta: ")
    if pregunta_estudiante.lower() == 'salir':
        print(f"🐱 Felix: ¡Adiós {nombre_usuario}! ¡Que tengas un buen día de estudio!")
        break
    print(felix.responder(pregunta_estudiante, usuario=nombre_usuario))

"""# Task
The task is to enhance the intelligence and responsiveness of the 'Felix' GPT agent by expanding its internal knowledge base and implementing more dynamic response mechanisms. This involves three main subtasks: (1) Ampliar la Base de Conocimiento de Preguntas y Respuestas (local_qa), (2) Expandir el Conocimiento Temático (conocimientos), and (3) Introducir Mecanismos de Respuesta Condicionales/Contextuales Simples. The final task is to confirm that these expansions lead to a more intelligent and less repetitive behavior from Felix and present the improvements to the user.

## Ampliar la Base de Conocimiento de Preguntas y Respuestas (local_qa)

### Subtask:
Incrementar significativamente el número de entradas en el diccionario `self.local_qa` de Felix. Esto incluye añadir más patrones de preguntas para categorías existentes y nuevas, así como una mayor diversidad de respuestas para cada patrón. El objetivo es cubrir un espectro más amplio de interacciones y reducir la repetición.
"""