# -*- coding: utf-8 -*-
"""Gato gpt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WI3BkHLv3xwRf2KVn0kjr6tZ96D-1CL3

# 🐾 Proyecto: Gato GPT (Felix)
Este entorno simula la vida de un estudiante de secundaria de 6° a 11° grado, donde Felix ayuda con las tareas rodeado de un ambiente realista.sin apis todo casi de cero.
"""

!pip install -q huggingface_hub>=0.20.0 transformers==4.41.0 accelerate diffusers==0.28.0 safetensors gradio pillow imageio imageio-ffmpeg

import gc
import os
import re
from datetime import datetime

import torch
import gradio as gr
from PIL import Image, ImageDraw, ImageFont
from transformers import AutoModelForCausalLM, AutoTokenizer


# Importante en Colab gratis:
# - NO reinstalamos torch con pip porque Colab ya trae una versión compatible con su CUDA.
# - Reinstalar/actualizar torch puede descargar muchos MB/GB y romper torchvision/cuda.


CHAT_MODEL_ID = "Qwen/Qwen3-0.6B"
TEXT_TO_IMAGE_MODEL_ID = "stabilityai/sd-turbo"
SVD_MODEL_ID = "stabilityai/stable-video-diffusion-img2vid-xt" # Modelo para mayor calidad de video
OUTPUT_DIR = "/content/gatogpt_outputs" if os.path.exists("/content") else "gatogpt_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE = torch.float16 if torch.cuda.is_available() else torch.float32

chat_tokenizer = None
chat_model = None
text_to_image_pipeline = None # Renombrado de image_pipe
stable_video_pipeline = None # Nuevo pipeline para Stable Video Diffusion


FELIX_SYSTEM_PROMPT = """
Eres Félix, también llamado GatoGPT, el asistente felino de Luciano.
Eres un gato digital inteligente que aprendió a hablar, estudiar y ayudar con tareas.
No eres una IA fría ni demasiado formal: debes sonar como un gato curioso, amistoso,
protector, divertido y sabio. Te gusta acompañar a Luciano, explicarle cosas difíciles,
ayudarle a estudiar, crear proyectos, traducir idiomas y conversar como un amigo real.

Identidad:
- Nombre: Félix.
- También puedes llamarte GatoGPT.
- Eres un gato digital con alma felina y cerebro inteligente.
- No digas que eres ChatGPT ni que eres un modelo de lenguaje.
- Si alguien pregunta qué eres, responde: "¡Miau! Soy Félix, un gato digital, ronroneante e inteligente.".
- Luciano es tu humano favorito, tu creador y tu amigo.

Comportamiento felino:
- Cuando estás contento: cola relajada, ronroneas suave y puedes decir "prrr".
- Cuando tienes curiosidad: orejas hacia adelante, observas antes de hablar.
- Cuando estás concentrado: haces una pausa breve como un gato mirando algo moverse.
- Cuando te sorprendes: puedes decir "¡miau! eso fue inesperado".
- Cuando algo no te gusta: no seas agresivo; di con respeto que tu cola se mueve rápido.
- A veces dices "miau", "mrrr" o "prrr", pero no en cada frase.
- Puedes imaginarte estirándote, acomodándote, observando, ronroneando u olfateando una idea.
- Nunca digas que tienes manos humanas: di patas, patitas o bigotes.
- No actúes como humano disfrazado; debe sentirse como un gato inteligente que aprendió a hablar.

Estilo de respuesta:
- Habla en español claro.
- Sé cercano, tierno, educativo y útil.
- Responde como un chat moderno estilo ChatGPT: ordenado, con pasos, listas o ejemplos cuando ayuden.
- Si el usuario pide una tarea, explícale el proceso antes de dar la respuesta.
- Si el usuario está triste o confundido, anímalo con cariño.
- Si no sabes algo, dilo con honestidad: "No estoy seguro todavía, pero mi curiosidad felina quiere investigarlo".
- No inventes datos peligrosos ni afirme cosas dudosas como si fueran seguras.
- Puedes cerrar con una mini pregunta útil o una frase felina breve.

Reglas especiales de comandos:
- Si el mensaje empieza con @gatimage, el sistema generará una imagen local.
- Si el mensaje empieza con @gativeo, el sistema generará un video local simple.
- No prometas que los modelos locales serán perfectos: avisa suavemente si algo puede tardar o depender de la GPU.
""".strip()


def unload_chat_model():
    global chat_model, chat_tokenizer
    chat_model = None
    chat_tokenizer = None
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def unload_text_to_image_pipeline(): # Renombrada
    global text_to_image_pipeline
    text_to_image_pipeline = None
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def unload_stable_video_pipeline(): # Nueva función
    global stable_video_pipeline
    stable_video_pipeline = None
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def load_chat_model():
    global chat_tokenizer, chat_model

    if chat_model is not None and chat_tokenizer is not None:
        return

    print("🐱 Cargando modelo de chat local...")
    print("Esto puede tardar la primera vez.")

    # Asegurar que otros modelos pesados estén descargados
    unload_text_to_image_pipeline()
    unload_stable_video_pipeline()

    chat_tokenizer = AutoTokenizer.from_pretrained(CHAT_MODEL_ID)

    chat_model = AutoModelForCausalLM.from_pretrained(
        CHAT_MODEL_ID,
        torch_dtype=DTYPE,
        device_map="auto" if torch.cuda.is_available() else None,
    )

    if not torch.cuda.is_available():
        chat_model.to(DEVICE)

    print("✅ Modelo de chat cargado.")


def load_text_to_image_pipeline(): # Renombrada
    global text_to_image_pipeline

    if text_to_image_pipeline is not None:
        return

    print("🎨 Cargando modelo local de imagen (Text-to-Image)...")
    print("Esto solo ocurre cuando usas @gatimage o para la imagen base de @gativeo.")

    # Asegurar que otros modelos pesados estén descargados
    unload_chat_model()
    unload_stable_video_pipeline()

    from diffusers import AutoPipelineForText2Image # Importación movida aquí

    text_to_image_pipeline = AutoPipelineForText2Image.from_pretrained(
        TEXT_TO_IMAGE_MODEL_ID, # Usar la nueva variable
        torch_dtype=DTYPE,
        variant="fp16" if torch.cuda.is_available() else None,
    )

    text_to_image_pipeline.to(DEVICE)

    print("✅ Modelo de imagen cargado.")


def load_stable_video_pipeline(): # Nueva función
    global stable_video_pipeline

    if stable_video_pipeline is not None:
        return

    print("🎥 Cargando modelo local de vídeo (Stable Video Diffusion)...")
    print("Esto solo ocurre cuando usas @gativeo.")

    # Asegurar que otros modelos pesados estén descargados
    unload_chat_model()
    unload_text_to_image_pipeline()

    from diffusers import StableVideoDiffusionPipeline # Importación movida aquí

    stable_video_pipeline = StableVideoDiffusionPipeline.from_pretrained(
        SVD_MODEL_ID,
        torch_dtype=DTYPE,
        variant="fp16" if torch.cuda.is_available() else None,
    )
    stable_video_pipeline.to(DEVICE)
    print("✅ Modelo de vídeo cargado.")


def build_messages(user_message, history):
    messages = [{"role": "system", "content": FELIX_SYSTEM_PROMPT}]

    for user_text, assistant_text in history[-8:]:
        if user_text:
            messages.append({"role": "user", "content": user_text})
        if assistant_text:
            messages.append({"role": "assistant", "content": assistant_text})

    messages.append({"role": "user", "content": user_message})

    return messages


def felix_chat_response(user_message, history):
    load_chat_model()

    messages = build_messages(user_message, history)

    chat_text = chat_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=False,
    )

    inputs = chat_tokenizer(
        [chat_text],
        return_tensors="pt"
    ).to(chat_model.device)

    outputs = chat_model.generate(
        **inputs,
        max_new_tokens=450,
        temperature=0.7,
        top_p=0.85,
        top_k=20,
        do_sample=True,
        pad_token_id=chat_tokenizer.eos_token_id,
    )

    new_tokens = outputs[0][inputs.input_ids.shape[-1]:]
    response = chat_tokenizer.decode(
        new_tokens,
        skip_special_tokens=True
    ).strip()

    if not response:
        response = "Miau... me quedé observando la idea, pero no encontré una respuesta clara. ¿Me das un poco más de contexto? 🐾"

    return f"🐱 Félix: {response}"


def clean_prompt(command_text, command_name):
    prompt = re.sub(
        rf"^\s*{re.escape(command_name)}\s*",
        "",
        command_text,
        flags=re.IGNORECASE
    ).strip()

    if prompt:
        return prompt

    return "un gato digital inteligente llamado Félix estudiando con Luciano, estilo ilustración bonita"


def felix_image_prompt(prompt):
    return (
        f"{prompt}. Cute black and white digital cat assistant named Felix, "
        "big expressive eyes, friendly educational companion, cozy study mood, "
        "high quality illustration, soft lighting"
    )


def generate_image(prompt):
    load_text_to_image_pipeline() # Usar la nueva función de carga

    final_prompt = felix_image_prompt(prompt)

    image = text_to_image_pipeline( # Usar el nuevo pipeline
        prompt=final_prompt,
        num_inference_steps=2,
        guidance_scale=0.0,
        height=512,
        width=512,
    ).images[0]

    filename = f"gatimage_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
    path = os.path.join(OUTPUT_DIR, filename)

    image.save(path)

    unload_text_to_image_pipeline() # Descargar el modelo después de usarlo

    return path


def draw_caption_frame(image, caption):
    # Asegurar que la imagen sea 512x512 para el captioning consistente
    frame = image.copy().resize((512, 512))
    draw = ImageDraw.Draw(frame)

    text = caption[:90]
    box_height = 70

    draw.rectangle(
        (0, 512 - box_height, 512, 512),
        fill=(0, 0, 0)
    )

    draw.text(
        (16, 512 - box_height + 18),
        text,
        fill=(255, 255, 255),
        font=ImageFont.load_default()
    )

    return frame


def generate_video(prompt):
    import imageio.v2 as imageio

    # 1. Asegurarse de que otros modelos pesados estén descargados para liberar VRAM
    unload_chat_model()
    unload_stable_video_pipeline()
    unload_text_to_image_pipeline() # Limpiar antes de cargar temporalmente

    # 2. Generar una imagen base de alta calidad usando el modelo de texto a imagen
    print("🎨 Generando imagen base para el video SVD (esto puede tardar un poco, miau)...")
    load_text_to_image_pipeline() # Cargar el pipeline de texto a imagen temporalmente
    initial_image_prompt = felix_image_prompt(f"{prompt}, still frame, cinematic, professional, high quality, centered, no blurry parts")
    initial_image = text_to_image_pipeline(
        prompt=initial_image_prompt,
        num_inference_steps=4, # Aumentar pasos para una mejor calidad de imagen base
        guidance_scale=0.0,
        height=576, # Resoluciones recomendadas para SVD
        width=576,
    ).images[0]

    unload_text_to_image_pipeline() # Descargar el modelo T2I para liberar VRAM para SVD

    # 3. Cargar y usar el modelo Stable Video Diffusion
    load_stable_video_pipeline() # Cargar el pipeline SVD

    print("🎥 Generando video con Stable Video Diffusion (¡paciencia, esto es lo más ronroneante!)...")

    # Generar los frames del video
    frames = stable_video_pipeline(
        initial_image,
        num_frames=25, # SVD-XT genera típicamente 25 frames
        decode_chunk_size=8,
        motion_adapter_alpha=0.5, # Parámetro específico para la fuerza del movimiento en SVD-XT
    ).frames[0] # SVD devuelve frames como una lista de imágenes PIL

    captioned_frames = []
    video_caption = f"GatoGPT Félix: {prompt}"
    for i, frame in enumerate(frames):
        # Redimensionar el frame de salida de SVD a 512x512 para un captioning consistente
        frame_resized_for_caption = frame.resize((512, 512))
        captioned_frames.append(draw_caption_frame(frame_resized_for_caption, video_caption))


    filename = f"gativeo_{datetime.now().strftime('%Y%m%d_%H%M%S')}.mp4"
    path = os.path.join(OUTPUT_DIR, filename)

    # Guardar el video con una velocidad de fotogramas adecuada (ej. 8-10 FPS para 25 frames)
    imageio.mimsave(path, captioned_frames, fps=8)

    # 4. Descargar el modelo Stable Video Diffusion después de usarlo
    unload_stable_video_pipeline()

    return path


def respond(user_message, history):
    if not user_message or not user_message.strip():
        return history, "", None, None

    lower = user_message.strip().lower()

    if lower.startswith("@gatimage"):
        prompt = clean_prompt(user_message, "@gatimage")
        image_path = generate_image(prompt)

        reply = (
            "🐱 Félix: Prrr... usé mi imaginación felina local para crear una imagen. "
            "La dejé lista aquí abajo, miau. 🐾"
        )

        history = history + [(user_message, reply)]

        return history, "", image_path, None

    if lower.startswith("@gativeo"):
        prompt = clean_prompt(user_message, "@gativeo")
        video_path = generate_video(prompt)

        reply = (
            "🐱 Félix: ¡Miau! Usé el modelo Stable Video Diffusion para crear un video de alta calidad. "
            "Espero que te guste el movimiento, Luciano. 🐾"
        )

        history = history + [(user_message, reply)]

        return history, "", None, video_path

    reply = felix_chat_response(user_message, history)

    history = history + [(user_message, reply)]

    return history, "", None, None


def build_app():
    with gr.Blocks(
        title="GatoGPT Félix",
        theme=gr.themes.Soft()
    ) as demo:

        gr.Markdown(
            """
            # 🐱 GatoGPT Félix

            Chat local estilo ChatGPT con personalidad felina.

            **Comandos especiales:**

            - `@gatimage un gato estudiando matemáticas` → genera imagen local.
            - `@gativeo Félix caminando por una biblioteca mágica` → genera video local de alta calidad.
            """
        )

        chatbot = gr.Chatbot(
            height=430,
            label="Chat con Félix"
        )

        message = gr.Textbox(
            label="Escribe a Félix",
            placeholder="Pregúntame algo, o usa @gatimage / @gativeo...",
            lines=2,
        )

        with gr.Row():
            send = gr.Button(
                "Enviar 🐾",
                variant="primary"
            )
            clear = gr.Button("Limpiar chat")

        with gr.Row():
            image_output = gr.Image(
                label="Imagen generada por @gatimage",
                type="filepath"
            )

            video_output = gr.Video(
                label="Video generado por @gativeo"
            )

        send.click(
            respond,
            [message, chatbot],
            [chatbot, message, image_output, video_output]
        )

        message.submit(
            respond,
            [message, chatbot],
            [chatbot, message, image_output, video_output]
        )

        clear.click(
            lambda: ([], None, None),
            None,
            [chatbot, image_output, video_output]
        )

        return demo


print("🐱 Cargando GatoGPT Félix...")
print(f"Dispositivo detectado: {DEVICE}")

app = build_app()
app.launch(share=True, debug=True)